name: restobuy_restaurant_flutter
description: Restobuy Restaurant Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0
versionCode: 1
versionName: 1.0.0

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  http: ^0.13.4
  dartz: ^0.10.1
  google_fonts: ^2.2.0
  flutter_svg: ^1.0.0
  cached_network_image: ^3.2.0
  path_provider: ^2.0.8
  youtube_player_flutter: ^8.0.0
  flutter_animator: ^3.2.0
  lottie: ^1.2.1
  image_picker: ^0.8.4+4
  firebase_core: ^1.11.0
  firebase_messaging: ^11.2.5
  #to push notification when app is in foreground
  flutter_local_notifications: ^9.2.0
  shared_preferences: any
  native_pdf_view: ^5.0.0
  intl: ^0.17.0
  html: ^0.15.0
  #cart badges count
  provider: ^6.0.2
  badges: ^2.0.2
  carousel_slider: ^4.0.0
  flutter_cached_pdfview: ^0.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  #flutter_native_splash: ^1.3.3


flutter:
  uses-material-design: true

  assets:
    - assets/animations/gifs/
    - assets/animations/lottiefiles/
    - assets/icons/
    - assets/icons/pngs/
    - assets/icons/svgs/
    - assets/images/

  #fonts:
  #  - family: Roboto
  #    fonts:
  #      - asset: assets/fonts/Roboto.ttf

